import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import PrelineScript from './PrelineScript'
import {Head} from "next/document";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <Head>
            <meta name="google-site-verification" content="-NttIeCsNFX7bi_Rj6onoCpyFICL51IJWnNl0mwkE2U"/>
        </Head>
        <body>
        <Navbar/>
        <main>
            {children}
        </main>
        <Footer/>
        <PrelineScript/>
        </body>
        </html>
    )
}
